### ISSUE TITLE
Misleading job cycle time given in error message

### ISSUE THREAD

**Issue by jasonlharvey** [nasa/TrickHLA#6] opened 2020-06-09 13:30 UTC
The error message output when look-ahead time is not less than data cycle time is misleading.  

I had set the data cycle time to 0.05 seconds but forgot to set the look-ahead time, and the expected error message still says my data cycle time was 0.1 seconds.  I verified that my data was actually cycling at 20 Hz, so it's just a misleading message.  The misleading part is highlighted below:
 
Manager::determine_job_cycle_time():2117 ERROR: The cycle time for this job is less than the HLA lookahead time! The HLA Lookahead time (0.1 seconds) must be less than or equal to the job **cycle time (0.1 seconds)**. Make sure 'lookahead_time' in your input or modified-data file is less than or equal to the 'THLA_DATA_CYCLE_TIME' time specified in the S_define file for the send_requested_data(), send_cyclic_data(), and receive_cyclic_data() jobs.

**Comment by dandexter** [comment] 2020-06-09 15:13
We get the job cycle from Trick using this call right before the error message:
job_cycle_time = exec_get_job_cycle( NULL );

Do you have have a default job cycle time specified that is getting overwritten at runtime?  If so this could be the cause of the job cycle time not being what you expected.

**Comment by dandexter** [comment] 2020-06-09 15:16
I see the error now and I will fix it.

**Comment by dandexter** [comment] 2020-06-09 15:23
Fix has been pushed.

**Closed by dandexter** 2020-06-09 15:23 UTC
